services:
  user-service:
    image: ${DOCKER_USERNAME}/user-service:latest
    ports:
      - "8081:8081"

  product-service:
    image: ${DOCKER_USERNAME}/product-service:latest
    ports:
      - "8082:8082"